stages:
- stage: Build
  jobs:
  - job: Build
    continueOnError: true
    steps:
     - task: ShellScript@2
       inputs:
        scriptPath: ./run.sh
       groovy:
         - script: >
            println("This is Groovy script!");
